### ISSUE TITLE
How to specify name of layer

### ISSUE THREAD

**Issue by sachinguptahsc** [agutoli/serverless-layers#110]
Hello,

This is more of a question. I am not able to find a way to define name of layer. If we can define name of layer then, it will be easy to use it in different environment.

**Comment by agutoli** [comment]
Hi @sachinguptahsc, currently, it doesn't allow specifying the whole layer name. Its probably a good idea. But you can change the suffix name like:

`<stack-name>-<stage>-<runtime>-<suffix>`

```yaml
custom:
  serverless-layers:
    - the-layer-suffix-name:
      ...options
    - the-other-layer-suffix-name:
        ...options
```
