### ISSUE TITLE
Python Layers using other layers packages

### ISSUE THREAD

**Issue by asyarif93** [agutoli/serverless-layers#114]
Using serverless-layers 2.5.3

when sls deployed, the all layers using same packages resulting `AWS Error: Function code combined with layers exceeds the maximum allowed size of 262144000 bytes` like #51

the extreme example was deliver_report, which supposed to have size of 300kb now have size of 70mb

config
```
custom:
  serverless-layers:
    - base:
        functions:
          - ...
        dependenciesPath: layers/base/requirements.txt
    - ...
    - deliver_report:
        functions:
          - deliver_report
        dependenciesPath: layers/deliver_report/requirements.txt
```

layers/base/requirements.txt
```
numpy
pandas
pyarrow
sqlalchemy
pytz
slackclient
```

layers/deliver_report/requirements.txt
```
xlsxwriter==1.4.5
```

```
-rw-r--r--   1 user  staff    60M Jun 24 10:51 data-test-m1-python-base.zip
-rw-r--r--   1 user  staff    80M Jun 24 10:57 data-test-m1-python-deliver_report.zip
-rw-r--r--   1 user  staff    69M Jun 24 10:53 data-test-m1-python-gcp.zip
-rw-r--r--   1 user  staff    72M Jun 24 10:56 data-test-m1-python-gcs.zip
-rw-r--r--   1 user  staff    72M Jun 24 10:55 data-test-m1-python-pubsub.zip
-rw-r--r--   1 user  staff    72M Jun 24 10:56 data-test-m1-python-report.zip
```
