### ISSUE TITLE
package.exclude from the serverless.yml is being ignored 

### ISSUE THREAD

**Issue by stanyq4** [agutoli/serverless-layers#118]
In the serverless.yml, I am specifying the following node modules to be excluded as part of the layer: 

```
package:
  excludeDevDependencies: true
  exclude:
    - node_modules/@aws-sdk/**
    - node_modules/@azure/**
    - node_modules/@baemingo/**
    - node_modules/sqreen/**
    - node_modules/sqreen-info/**
```

AWS SDK is around 50MB and is included by default in all lambdas, so it makes no sense to package it as part of the layer. 

However, when the layer is being created it still includes the @aws-sdk folder from node_modules

`Created layer package /Users/stanyeshchenko/Dev/projects/api-demo/.serverless/api-demo-nodejs-default.zip (88.9 MB)`

Attaching a screenshot with layer that I downloaded from S3, you can see that aws-sdk is not excluded  

<img width="937" alt="Screen Shot 2022-10-01 at 11 19 39 AM" src="https://user-images.githubusercontent.com/23194864/193416310-a84e2644-44c8-4eca-80a9-6a66145c9fc1.png">

**Comment by agutoli** [comment]
PR to review:
https://github.com/agutoli/serverless-layers/pull/131

## Usage:

```yaml
package:
  patterns:
    - '!node_modules/express/**'
    - 'node_modules/**'
```

Reference:
https://www.serverless.com/framework/docs/providers/aws/guide/packaging

**Comment by lmzbonack** [comment]
If you could merge this bad boy that would be pretty cool. Thanks

**Comment by fyelci** [comment]
@agutoli Thanks for the fix. Can you please merge it?

**Comment by m0uneer** [comment]
As a workaround, install `clean-modules` npm module and use `customInstallationCommand` option to call  `npm ci --omit=dev --ignore-scripts && clean-modules -y` and set up a `.cleanmodules` file with the patterns you want to exclude.


Bonus: If you want to include, you can use this undocumented option `copyBeforeInstall`
```yaml
  serverless-layers:
    copyBeforeInstall:
      - package-lock.json
      - path/to/custom/files # This file will be part of the layers
```
