### ISSUE TITLE
[LayersPlugin]: Error: Can not find yarn.lock!

### ISSUE THREAD

**Issue by mattnakatani** [agutoli/serverless-layers#21]
despite the yarn.lock existing, I am getting this error when I try to use yarn.lock in custom:packagePath:

**Comment by agutoli** [comment]
You can not pass `yarn.lock` to custom:packagePath. That option is just for `package.json` file. If you have a project which package.json is not in the root folder for example, you can do like:

```yml
custom:
  serverless-layers:
    packagePath: ./MyCustomFolder/package.json
```

**Comment by agutoli** [comment]
Yes, It has "yarn.lock" support already.

I can see here:
https://github.com/agutoli/serverless-layers/blob/master/src/package/Dependencies.js#L53

**Comment by mattnakatani** [comment]
right but it still doesn't work with my yarn lock

**Comment by agutoli** [comment]
Ok, can you share your `custom` settings?
```yml
Like:
custom:
  serverless-layers:
    packagePath: ./MyCustomFolder/package.json
```

**Comment by mattnakatani** [comment]
`custom:
  serverless-layers:
    packageManager: yarn
    compatibleRuntimes: ['nodejs','nodejs10.x']
    packagePath: ../yarn.lock`

**Comment by agutoli** [comment]
@mattnakatani You option is wrong.

<img width="978" alt="Screen Shot 2019-09-16 at 4 50 57 pm" src="https://user-images.githubusercontent.com/298845/64938730-352db400-d8a2-11e9-9158-033a9f3084cb.png">

Please try:

```yml
custom: 
  serverless-layers:
     packageManager: yarn
```

It should work.
