### ISSUE TITLE
Need help to use this plugin with serverless-webpack

### ISSUE THREAD

**Issue by hoang-innomizetech** [agutoli/serverless-layers#27]
I am also looking to use this plugin for our serverless project with TypeScript. We use serverless-webpack plugin to bundle the TypeScript code and also have an option to include/exclude node_modules from the service .zip file. 

Basically, we can know what exactly packages need for the current build, so I am trying to see whether we can create a temporary package.json, install dependencies and create layer and deploy.

**Comment by agutoli** [comment]
Nice, @hoang-innomizetech. Feel free to ask any question about that plugin.

Usage example

```yml
plugins:
  - serverless-layers
  
custom:
  serverless-layers:
    # It will be attached to all functions
    - common:
        dependenciesPath: ./package.json
    # It will be attached to my_func2
    - myLayerB:
        functions:
          - my_func2
        dependenciesPath: ./package-custom-name.json
    # It will be attached to my_func1 and my_func2
    - myExistentLayer:
        functions:
          - my_func1
          - my_func2
        arn: arn:aws:lambda:us-east-1:<your_account>:layer:my-existent-layer

functions:
  my_func1:
    handler: handler.hello
  my_func2:
    handler: handler.hello
  my_func3:
    handler: handler.hello
```
