### ISSUE TITLE
Associate multiple layers with different functions

### ISSUE THREAD

**Issue by CartierDiamonds** [agutoli/serverless-layers#29]
Currently in my serverless.yml i have 2 functions defined but i only want my custom layer to be associated with 1 of the functions. Is it possible to define multiple layers and choose which layer is associated with which lambda?

**Comment by agutoli** [comment]
@CartierDiamonds I just pushed a new version with that feature.

Can you try `2.1.0` version, please?

Usage Example
```
custom:
  serverless-layers:
    # applies for all lambdas 
    - common:
        dependenciesPath: ./my-folder/package.json
    # apply for foo only
    - foo:
        functions:
          - foo
        dependenciesPath: my-folder/package-foo.json
    - staticArn:
        functions:
          - foo
          - bar
        arn: arn:aws:lambda:us-east-1:<your_account>:layer:node-v13-11-0:5

functions:
  foo:
    handler: handler.hello
  bar:
    handler: handler.hello

plugins:
  - serverless-layers
```
