### ISSUE TITLE
this.provider.getDeploymentPrefix is not a function

### ISSUE THREAD

**Issue by keithcoughtrey** [agutoli/serverless-layers#3]
I've followed the instructions. The relevant parts of my serverless.yml are:

```
provider:
  deploymentBucket: #required!
    name: "layers_deployment_bucket"

plugins:
  - serverless-layers

package:
  individually: false
  exclude:
    - node_modules/**
  excludeDevDependencies: true

```
But when I try to deploy I get:

Type Error ---------------------------------------------
 
  this.provider.getDeploymentPrefix is not a function

**Comment by agutoli** [comment]
Hi, @keithcoughtrey . Let me know some informations plz.

```
serverless version
node version
npm version
```

**Comment by agutoli** [comment]
I fixed this specific problem but I think you are using some old version of `serverless` (I am not sure). 

Try this new version plz: 1.1.1

Note: I still need to know what version you are using.

**Comment by keithcoughtrey** [comment]
I appreciate your quick response

serverless version 1.35.1
node version 8.10
npm version 5.60

I was using serverless-layers 1.1.0. 
I'm now using 1.1.1 and that gets me passed this problem and on to a new one:

Serverless: [LayersPlugin]: Downloading package.json from bucket...
Serverless: [LayersPlugin]: package.json does not exists at bucket...
 
  Type Error ---------------------------------------------
 
  this.provider.naming.getLambdaLayerOutputLogicalId is not a function

**Comment by agutoli** [comment]
Hey, @keithcoughtrey . Thats is so weird for me. 

Have you specified provider name? 

```yml
provider:
  name: aws
  runtime: nodejs8.10
```
