### ISSUE TITLE
2.2.0 Broken when single layer config has 2 or more options

### ISSUE THREAD

**Issue by sizuhiko** [agutoli/serverless-layers#32]
Hi,

For example, Single layer config from README followings:

```yaml
custom:
  serverless-layers:
    functions: # optional
      - my_func2
    dependenciesPath: ./package.json
```
In this case occurs error `It looks like you are trying to setup a list of layers, no?` from version 2.2.0.

This validation logic was added by [this commit](https://github.com/agutoli/serverless-layers/commit/85e8070744ae6d79b136da470e3188964c0b7a22).

`const keys = Object.keys(inboundSettings);` are `functions` and `dependenciesPath`.

2.2.0 not support for single layer config that has 2 or more options?
