### ISSUE TITLE
Adding this package makes deploying fail

### ISSUE THREAD

**Issue by talaikis** [agutoli/serverless-layers#41]
Error: `... ○ "undefined" is not supported (yet).`

Config:

```
custom:
  serverless-layers:
    dependenciesPath: requirements.txt
    compatibleRuntimes: ["python3.8"]
```

Env:

`
Operating System:          win32
     Node Version:              12.16.1
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.0
     Components Version:        Unavailable
`
