### ISSUE TITLE
TypeError: Cannot read property 'pipesCount' of undefined

### ISSUE THREAD

**Issue by revmischa** [agutoli/serverless-layers#42]
TypeScript nestjs application. I can deploy fine with serverless-layers disabled.
Using `"serverless-layers": "^2.2.4"`
```
❯ sls deploy


Serverless: [ LayersPlugin ]: => default
... ○ Downloading package.json from bucket...
... ○ Comparing package.json dependencies...
... ○  Changes identified ! Re-installing...
... ∅ [warning] ".npmrc" file does not exists!
... ∅ [warning] "yarn.lock" file does not exists!
npm WARN nesttest@0.0.0 No repository field.
npm WARN nesttest@0.0.0 No license field.


> @nestjs/core@7.0.13 postinstall /Users/cyber/dev/jb/demo/aws-node-typescript-nest/.serverless/layers/nodejs/node_modules/@nestjs/core
> opencollective || exit 0

added 243 packages from 445 contributors and audited 2810 packages in 12.682s

4 packages are looking for funding
  run `npm fund` for details

found 1400 vulnerabilities (64 low, 1336 high)
  run `npm audit fix` to fix them, or `npm audit` for details


  Type Error ---------------------------------------------

  TypeError: Cannot read property 'pipesCount' of undefined
      at ReadStream.Readable.pipe (_stream_readable.js:623:17)
      at Readable.<anonymous> (/Users/cyber/dev/jb/demo/aws-node-typescript-nest/node_modules/lazystream/lib/lazystream.js:33:12)
      at Readable.instance.<computed> (/Users/cyber/dev/jb/demo/aws-node-typescript-nest/node_modules/lazystream/lib/lazystream.js:18:14)
      at Readable.read (/Users/cyber/dev/jb/demo/aws-node-typescript-nest/node_modules/lazystream/node_modules/readable-stream/lib/_stream_readable.js:443:10)
      at resume_ (/Users/cyber/dev/jb/demo/aws-node-typescript-nest/node_modules/lazystream/node_modules/readable-stream/lib/_stream_readable.js:790:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
      at runNextTicks (internal/process/task_queues.js:66:3)
      at processImmediate (internal/timers.js:429:9)
      at process.topLevelDomainCallback (domain.js:137:15)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.3
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.0
     Components Version:        2.30.11
```

```yaml
service:
  name: aws-node-typescript-nest

plugins:
  - serverless-offline
  - serverless-layers
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket: aaaaa-layers
  region: eu-west-1

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          cors: true
          path: "/"
          method: any
      - http:
          cors: true
          path: "{proxy+}"
          method: any
```
