### ISSUE TITLE
python packages accumulate

### ISSUE THREAD

**Issue by pecirep** [agutoli/serverless-layers#44]
I'm trying to create separate layers for dependencies in a python3.8-based project, as not all functions need all dependencies. 
I was surprised by the sizes of the generated zip files so I downloaded them from the bucket and realized that dependencies were being accumulated in the order of the list.

Each of these requirements.txt files only contains a single requirement (python-jose, pyjwt[crypto] and requests respectively) and while the python-jose layer works correctly, pyjwt-crypto contains both pyjwt[crypto] and python-jose and the requests layer contains all 3 dependencies.

```
package:
  individually: true
  exclude:
    - ./**

custom:
  serverless-layers:
    - python-jose:
        functions:
          - function1
        dependenciesPath: layers/python-jose/requirements.txt
    - pyjwt-crypto:
        functions:
          - function2
        dependenciesPath: layers/pyjwt-crypto/requirements.txt
    - requests:
        functions:
          - function1
          - function3
          - function4
        dependenciesPath: layers/requests/requirements.txt
```
