### ISSUE TITLE
Feature request: allow add more static layer

### ISSUE THREAD

**Issue by c19** [agutoli/serverless-layers#54]
for example:
```
- staticArn:
        functions:
          - func
        arn:
          - arn:aws:lambda:ap-northeast-1:xxx:layer:linux-utility:8
          - arn:aws:lambda:ap-northeast-1:xxx:layer:python3:1
```

**Comment by c19** [comment]
Oh, Just realize that `staticArn` is arbitrary. 
```
- linux-utility:
        functions:
          - func
        arn:
          - arn:aws:lambda:ap-northeast-1:xxx:layer:linux-utility:8
- linux-utility:
        functions:
          - func
        arn:
          - arn:aws:lambda:ap-northeast-1:xxx:layer:python3:1
```

this will do.
