### ISSUE TITLE
Plugin does not respect serverSideEncryption flag

### ISSUE THREAD

**Issue by lferreira-tenchi** [agutoli/serverless-layers#72]
When the deployment bucket has encryption enabled:

```
deploymentBucket:
    name: exampleBucket
    serverSideEncryption: AES256
```

The plugin does not respect the serverSideEncryption flag and attempts to upload without encryption resulting in an error.
The plugin should also support a similar object on the layersDeploymentBucket:

```
serverless-layers:
    packageManager: npm
    layersDeploymentBucket:
        name: exampleBucket
        serverSideEncryption: AES256
```

This feature is desired as some organizations enforce encryption on all buckets as a security guideline
