### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'pipes')

### ISSUE THREAD

**Issue by andreyvital** [agutoli/serverless-layers#80]
Hey—I'm getting the following error:

```
  TypeError: Cannot read properties of undefined (reading 'pipes')
      at ReadStream.Readable.pipe (node:internal/streams/readable:658:13)
      at Readable.<anonymous> (/Users/(...)/Projects/(...)/api/node_modules/lazystream/lib/lazystream.js:33:12)
      at Readable.instance.<computed> (/Users/(...)/Projects/(...)/api/node_modules/lazystream/lib/lazystream.js:18:14)
      at Readable.read (/Users/(...)/Projects/(...)/api/node_modules/lazystream/node_modules/readable-stream/lib/_stream_readable.js:443:10)
      at resume_ (/Users/(...)/Projects/(...)/api/node_modules/lazystream/node_modules/readable-stream/lib/_stream_readable.js:790:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at processImmediate (node:internal/timers:437:9)
```

I've tried debugging what's the root cause, but no luck.

Versions:
```
api % cat node_modules/serverless-layers/node_modules/archiver/package.json |jq .version
"3.1.1"
api % cat node_modules/serverless-layers/package.json |jq .version
"2.5.1"
api % cat node_modules/serverless/package.json |jq .version
"2.67.0"
```

Settings (serverless.yml):
```
serverless-layers:
  packageManager: npm
  compileDir: .serverless
  forceInstall: ${env:SERVERLESS_LAYERS_FORCE_INSTALL, false}
  dependenciesPath: package.json
  compatibleRuntimes: ["nodejs"]
  layersDeploymentBucket: (...)
  # Why ../../..? Because the script runs on `.serverless/layers/nodejs`
  customInstallationCommand: "../../../scripts/build/install-node-modules.sh"
```

**install-node-modules.sh**
```SH
echo "Installing dependencies: $(pwd)"
npm install --loglevel=error --no-optional --only=production --audit=false
npm prune --production --audit=false

echo "Running https://github.com/tj/node-prune"
node-prune --exclude "*.d.ts" ./node_modules
```
