### ISSUE TITLE
provider.deploymentBucket is specified, yet error is reported that it isn't

### ISSUE THREAD

**Issue by bitsofinfo** [agutoli/serverless-layers#82]
Using serverless 0.70.0 and the latest serverless-layers plugin

error:
```
Serverless: [ LayersPlugin ]: => default
 
 Error ---------------------------------------------------
 
  Error: Please, you should specify "deploymentBucket" or "layersDeploymentBucket" option for this plugin!
```

serverless.yml snippets:
```
provider:
   ...
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
    serverSideEncryption: AES256
    tags: # Tags that will be added to each of the deployment resources
      MyEnv: ${opt:stage, 'dev'}
      MyApp: ${self:service.name}

....

custom:
  serverless-layers:
    dependenciesPath: ./package.json
    compatibleRuntimes: 
      - nodejs14.x

```

**Comment by sofianekorbi** [comment]
Same error 🙃

**Comment by agutoli** [comment]
Sorry for the late reply (very busy currently). So, it seems you was not specifying bucket name. 

```yaml
provider:
   ...
  deploymentBucket:
    name: your-bucket
    maxPreviousDeploymentArtifacts: 10
    ...
```

Or

```yaml
custom:
  serverless-layers:
    layersDeploymentBucket: your-bucket
    dependenciesPath: ./package.json
    ....
```

I'm closing this issue.
