### ISSUE TITLE
Not automatically attaching layer to function

### ISSUE THREAD

**Issue by NeilJ247** [agutoli/serverless-layers#95]
I have a single function but when running sls deploy it is not attaching the layer to it.  I've tried defining the function in the serverless-layers config but it just skips it.

Related output:

```
(Skipped) function.contactVerified - because it has no other layers
```

Config:
```
custom:
  serverless-layers:
    dependenciesPath: ./lambda/layers/package.json
    layersDeploymentBucket: mybucket

functions:
  contactVerified:
    timeout: 900
    handler: lambda-dist/lambda/src/functions/contact-verified.handler

```

Serverless info:

```
sls --version
Framework Core: 2.72.3
Plugin: 5.5.4
SDK: 4.3.1
Components: 3.18.2
```
