### ISSUE TITLE
Resource not defined when no functions present

### ISSUE THREAD

**Issue by srdcarrion** [agutoli/serverless-layers#96]
I want to deploy just layers. I.e. no functions or resources included. When doing so this error fires:

`The CloudFormation template is invalid: Template format error: At least one Resources member must be defined.`

On review of the template in ./.serverless/ there is no resources. I can only get around this by adding a dummy resource to the serverless.yaml:

```
resources:
  Resources:
    NullResource:
      Type: AWS::CloudFormation::WaitConditionHandle
```

I'd expect to see a "AWS::Lambda::LayerVersion" resource type.

Any reason why this might be the case?
